name: BigQuery_Project_1
description: ''
version: '1.0'
author: shashank@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: bigqueryproject1
  parentArtefactID: shashankprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-02-17 10:24:53'
pipelines:
  pipelines/bigquery_mig:
    name: bigquery_mig
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-02-17 10:24:53'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/bigquery:
      name: bigquery
      category: Source/Target
      subCategory: Warehouse
      description: null
      author: shashank@prophecy.io
      mode: batch
      files:
      - shashankprophecyioteam_bigqueryproject1/gems/bigquery.py
      gemType: DatasetGem
      dependencies: []
      createdAt: '2025-02-17 10:25:07'
  dependencies: null
functions:
  author: null
  createdAt: '2025-02-17 10:24:53'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-02-17T10:24:53.282673Z'
  name: plibMaven
  version: 8.8.1
  id: '1870749324'
  createdAt: '2025-02-17T10:24:53.282673Z'
  type: plibMaven
- modifiedAt: '2025-02-17T10:24:53.282673Z'
  name: plibPypi
  version: 1.9.33
  id: '129977696'
  createdAt: '2025-02-17T10:24:53.282673Z'
  type: plibPypi
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2025-02-17 10:24:20'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.40
    isDefault: true
    author: null
    createdAt: '2025-02-17 10:24:20'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
